config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :cancellation_forms
  resources :complaint_forms
  resources :site_updates
  resources :skill_lists
  resources :completed_websites
  resources :confirmation_forms
  resources :website_requests
  resources :user_informations
  devise_for :admins
  devise_for :users
  root to: "pages#home"

  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'admin#primary', as: :admin_root
  get '/skill_lists', to: 'skill_lists#index', as: :skills
  get '/completed_websites', to: 'completed_websites#index', as: :finished_website
  get '/confirmation_forms', to: 'confirmation_forms#index', as: :confirming
  get '/user_informations', to: 'user_informations#index', as: :user_info
  get '/website_requests', to: 'website_requests#index', as: :requests
  get '/cancellation_forms', to: 'cancellation_forms#index', as: :cancel
  get '/complaint_forms', to: 'complaint_forms#index', as: :complain
  get '/site_updates', to: 'site_updates#index', as: :news
  delete "/logout", to: "sessions#destroy"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/complaint_forms_controller.rb
class ComplaintFormsController < ApplicationController
  before_action :set_complaint_form, only: %i[ show edit update destroy ]

  # GET /complaint_forms or /complaint_forms.json
  def index
    @complaint_forms = ComplaintForm.all
  end

  # GET /complaint_forms/1 or /complaint_forms/1.json
  def show
  end

  # GET /complaint_forms/new
  def new
    @complaint_form = ComplaintForm.new
  end

  # GET /complaint_forms/1/edit
  def edit
  end

  # POST /complaint_forms or /complaint_forms.json
  def create
    @complaint_form = ComplaintForm.new(complaint_form_params)
    @complaint_form.user = current_user

    respond_to do |format|
      if @complaint_form.save
        format.html { redirect_to complaint_form_url(@complaint_form), notice: "Complaint form was successfully created." }
        format.json { render :show, status: :created, location: @complaint_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @complaint_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaint_forms/1 or /complaint_forms/1.json
  def update
    respond_to do |format|
      if @complaint_form.update(complaint_form_params)
        format.html { redirect_to complaint_form_url(@complaint_form), notice: "Complaint form was successfully updated." }
        format.json { render :show, status: :ok, location: @complaint_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @complaint_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaint_forms/1 or /complaint_forms/1.json
  def destroy
    @complaint_form.destroy

    respond_to do |format|
      format.html { redirect_to complaint_forms_url, notice: "Complaint form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint_form
      @complaint_form = ComplaintForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def complaint_form_params
      params.require(:complaint_form).permit(:complaint_title, :complaint_description, :time_of_event, :user_id)
    end
end

app/views/complaint_forms/_complaint_form.html.erb
<div id="<%= dom_id complaint_form %>">
  <p>
    <strong>Complaint title:</strong>
    <%= complaint_form.complaint_title %>
  </p>

  <p>
    <strong>Complaint description:</strong>
    <%= complaint_form.complaint_description %>
  </p>

  <p>
    <strong>Time of event:</strong>
    <%= complaint_form.time_of_event %>
  </p>

  <%# <p>
    <strong>User:</strong>
    <%= complaint_form.user_id %>
  <%# </p> %>

</div>

app/views/complaint_forms/_form.html.erb
<%= simple_form_for(@complaint_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :complaint_title %>
    <%= f.input :complaint_description %>
    <%= f.input :time_of_event %>
    <%# <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/complaint_forms/edit.html.erb
<h1>Editing complaint form</h1>

<%= render "form", complaint_form: @complaint_form %>

<br>

<div>
  <%= link_to "Show this complaint form", @complaint_form %> |
  <%= link_to "Back to complaint forms", complaint_forms_path %>
</div>

app/views/complaint_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Complaint forms</h1>

<div id="complaint_forms">
  <% @complaint_forms.each do |complaint_form| %>
    <%= render complaint_form %>
    <p>
      <%= link_to "Edit form", complaint_form,  class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    </p>
  <% end %>
</div>

<%= link_to "New Complaint", new_complaint_form_path,  class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
<%= link_to "Back to the main page", user_registration_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %><br>

app/views/complaint_forms/new.html.erb
<h1>New complaint form</h1>

<%= render "form", complaint_form: @complaint_form %>

<br>

<div>
  <%= link_to "Back to complaint forms", complaint_forms_path %>
</div>

app/views/complaint_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @complaint_form %>

<div>
  <%= link_to "Edit this complaint form", edit_complaint_form_path(@complaint_form) %> |
  <%# <%= link_to "Back to complaint forms", complaint_forms_path %>

  <%= button_to "Destroy this complaint form", @complaint_form, method: :delete %>
  <%= link_to "Back to the main page", user_registration_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
</div>