config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :cancellation_forms
  resources :complaint_forms
  resources :site_updates
  resources :skill_lists
  resources :completed_websites
  resources :confirmation_forms
  resources :website_requests
  resources :user_informations
  devise_for :admins
  devise_for :users
  root to: "pages#home"

  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'admin#primary', as: :admin_root
  get '/skill_lists', to: 'skill_lists#index', as: :skills
  get '/completed_websites', to: 'completed_websites#index', as: :finished_website
  get '/confirmation_forms', to: 'confirmation_forms#index', as: :confirming
  get '/user_informations', to: 'user_informations#index', as: :user_info
  get '/website_requests', to: 'website_requests#index', as: :requests
  get '/cancellation_forms', to: 'cancellation_forms#index', as: :cancel
  get '/complaint_forms', to: 'complaint_forms#index', as: :complain
  get '/site_updates', to: 'site_updates#index', as: :news
  delete "/logout", to: "sessions#destroy"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user_information, dependent: :destroy
  has_many :website_requests, dependent: :destroy
  has_many :complaint_forms, dependent: :destroy
  has_many :cancellation_forms, dependent: :destroy
  has_and_belongs_to_many :confirmation_forms
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_information_form, only: %i[ show edit update destroy ]

  # GET /information_forms or /information_forms.json
  def primary
    @user = User.all
    @website_requests = WebsiteRequest.all
    @user_informations = UserInformation.all
  end

  # GET /user/1 or /user/1.json
  def show
    # @fuel_needed = @fuel_needed
    # @name = @name
    # @user = current_user
    @website_request.all
    @user = User.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
      info = JSON.parse(url_s)
      @infos = info["value"]
    render json: @current_user
  end

  def user
  end

  # GET /user/new
  def new
    @user = User.new
  end

  # GET /user/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    user = User.create(user_params)
    session[:user_id] = user.id
    render json:user, status: :created

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "Welcome to the BOS." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "Your account has been updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to user_url, notice: "user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
      params.permit(:username, :password, :password_confirmation)
    end
end

app/views/users/primary.html.erb
<div class="user_page">

  <%= link_to "user information", user_info_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
  <%= link_to "website request", requests_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
  <%# <%= link_to "review", reaction_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
  <%= link_to "complaint", complain_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
  <%= button_to "Log out", destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } }, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
  <%# <%= link_to "cancel order(s)", cancel_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>

  <div class="requests col-8">
    <% WebsiteRequest.all.each do |form|%>
      <div class="infobox">
        <strong><%= form.website_name %><br></strong>
          <%= form.why_website %><br>
          <%= form.website_description %><br>
          <%= form.deadline.strftime('%D') %><br>
          <%= link_to "Edit or Destroy", edit_website_request_path(form), class: "btn btn-pink text-grey fw-bold"  %>
          <%# <%= link_to "Delete request", website_request_path(form), method: :delete, class: "btn btn-pink text-grey fw-bold" %>
      </div>

    <% end %>
  </div>
  <div class="results col-4">
    <% ConfirmationForm.all.each do |form|%>
      <div class="infobox">
        <strong><%= form.project_assignment %><br></strong>
          <%= form.website_assessment %>
          <%= form.overall_comment %><br>
          <%= form.price_offer %><br>
          <%= form.deadline_possibility.strftime('%D') %><br>
      </div>
    <% end %>
  </div>
</div>