config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :cancellation_forms
  resources :complaint_forms
  resources :site_updates
  resources :skill_lists
  resources :completed_websites
  resources :confirmation_forms
  resources :website_requests
  resources :user_informations
  devise_for :admins
  devise_for :users
  root to: "pages#home"

  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'admin#primary', as: :admin_root
  get '/skill_lists', to: 'skill_lists#index', as: :skills
  get '/completed_websites', to: 'completed_websites#index', as: :finished_website
  get '/confirmation_forms', to: 'confirmation_forms#index', as: :confirming
  get '/user_informations', to: 'user_informations#index', as: :user_info
  get '/website_requests', to: 'website_requests#index', as: :requests
  get '/cancellation_forms', to: 'cancellation_forms#index', as: :cancel
  get '/complaint_forms', to: 'complaint_forms#index', as: :complain
  get '/site_updates', to: 'site_updates#index', as: :news
  delete "/logout", to: "sessions#destroy"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/skill_list.rb
class SkillList < ApplicationRecord
  belongs_to :admin
end

app/controllers/skill_lists_controller.rb
class SkillListsController < ApplicationController
  before_action :set_skill_list, only: %i[ show edit update destroy ]

  # GET /skill_lists or /skill_lists.json
  def index
    @skill_lists = SkillList.all
  end

  # GET /skill_lists/1 or /skill_lists/1.json
  def show
  end

  # GET /skill_lists/new
  def new
    @skill_list = SkillList.new
  end

  # GET /skill_lists/1/edit
  def edit
  end

  # POST /skill_lists or /skill_lists.json
  def create
    @skill_list = SkillList.new(skill_list_params)
    @skill_list.admin = current_user

    respond_to do |format|
      if @skill_list.save
        format.html { redirect_to skill_list_url(@skill_list), notice: "Skill list was successfully created." }
        format.json { render :show, status: :created, location: @skill_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @skill_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skill_lists/1 or /skill_lists/1.json
  def update
    respond_to do |format|
      if @skill_list.update(skill_list_params)
        format.html { redirect_to skill_list_url(@skill_list), notice: "Skill list was successfully updated." }
        format.json { render :show, status: :ok, location: @skill_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @skill_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_lists/1 or /skill_lists/1.json
  def destroy
    @skill_list.destroy

    respond_to do |format|
      format.html { redirect_to skill_lists_url, notice: "Skill list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill_list
      @skill_list = SkillList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skill_list_params
      params.require(:skill_list).permit(:skill, :admin_id)
    end
end

app/views/skill_lists/_form.html.erb
<%= simple_form_for(@skill_list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :skill %>
    <%= f.association :admin %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/skill_lists/_skill_list.html.erb
<div id="<%= dom_id skill_list %>">
  <p>
    <strong>Skill:</strong>
    <%= skill_list.skill %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= skill_list.admin_id %>
  </p>

</div>

app/views/skill_lists/edit.html.erb
<h1>Editing skill list</h1>

<%= render "form", skill_list: @skill_list %>

<br>

<div>
  <%= link_to "Show this skill list", @skill_list %> |
  <%= link_to "Back to skill lists", skill_lists_path %>
</div>

app/views/skill_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Skill lists</h1>

<div id="skill_lists">
  <% @skill_lists.each do |skill_list| %>
    <%= render skill_list %>
    <p>
      <%= link_to "Show this skill list", skill_list %>
    </p>
  <% end %>
</div>

<%= link_to "New skill list", new_skill_list_path %>

app/views/skill_lists/new.html.erb
<h1>New skill list</h1>

<%= render "form", skill_list: @skill_list %>

<br>

<div>
  <%= link_to "Back to skill lists", skill_lists_path %>
</div>

app/views/skill_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @skill_list %>

<div>
  <%= link_to "Edit this skill list", edit_skill_list_path(@skill_list) %> |
  <%= link_to "Back to skill lists", skill_lists_path %>

  <%= button_to "Destroy this skill list", @skill_list, method: :delete %>
</div>